name: Fuga Workflow

on:
  workflow_run:
    workflows:
      - "Hoge Workflow"
    branches:
      - master
      - add-fuga-workflow
    types:
      - completed

jobs:

  test1:

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v1

      - name: Hello
        run: echo hello FUGA
