name: Test GHA

on:
  - push

jobs:

  test:

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - uses: actions/checkout@v1

      - name: Check PWD
        run:
          pwd

      - name: Print ENV
        run:
          env
    
      - name: Run only in master branch
        if: github.ref == 'refs/heads/master'
        run:
          echo "hello 'refs/heads/master' branch"
