name: Test GHA

on:
  - push

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:

  test1:

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - uses: actions/checkout@v1

      - name: Check PWD
        run: pwd

      - name: Print ENV
        run: env | sort

      - name: Run mutli-line command
        run: |
          echo \
            "hoge" \
            "fuga" \
            "piyo"
          echo foo bar baz

      - name: set HOGE env
        run: |
          echo "::set-env name=HOGE::hogehoge"
          echo "::set-env name=FUGA::fugafuga"
          echo "::set-env name=PIYO::piyopiyo"

      - name: check HOGE env
        run: test -n "${HOGE}" && echo "${HOGE}"

      - name: Print ENV
        run: env | sort

  test2:

    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - name: Only Run in master branch
        run:
          echo "hello 'refs/heads/master' branch"

  test3:
    needs:
      - test1
      - test2

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - name: Only run if test1 and test2 succeed
        run:
          echo "test1 and test2 was succeed. run test3"

  test4:
    needs:
      - test1

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - name: Only run if test1 and test2 succeed
        run:
          echo "test1 was succeed. run test4"

  test5:
    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - name: Who will run
        run: whoami

      - name: Check `/var/lib/docker`
        run:
          sudo ls -l /var/lib/docker

      - name: Check size of `/var/lib/docker`
        run:
          sudo du -sh /var/lib/docker
