name: Test GHA

on:
  - push

jobs:

  test1:

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - uses: actions/checkout@v1

      - name: Check PWD
        run:
          pwd

      - name: Print ENV
        run:
          env
    
  test2:

    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    timeout-minutes: 3000

    steps:
      - name: Only Run in master branch
        run:
          echo "hello 'refs/heads/master' branch"

  test3:
    needs:
      - test1
      - test2

    steps:
      - name: Only run if test1 and test2 succeed
        run:
          echo "run test3"

